### ISSUE TITLE
Execution failed for task ':unityLibrary:BuildIl2CppTask'.

### ISSUE THREAD

**Issue by ahalyatriton** [azesmway/react-native-unity-play#25]
I tried  your example in android
<img width="685" alt="Capture" src="https://user-images.githubusercontent.com/52232100/160063935-06d5ad0a-39a9-4146-ae18-7157ebf78204.PNG">

**Comment by HermanLederer** [comment]
I ran into similar problem before but i don't remember the solution. It could be missing execution permisions on your gradle file

**Comment by azesmway** [comment]
> I tried your example in android <img alt="Capture" width="685" src="https://user-images.githubusercontent.com/52232100/160063935-06d5ad0a-39a9-4146-ae18-7157ebf78204.PNG">

My example is made on mac os, and you are trying to run it on windows. need to fix the path

**Comment by HermanLederer** [comment]
I don't use windows. I had that error on linux which means it should be similar on mac. Try
```
chmod 755 android/gradlew
```

**Comment by Ramesh21071993** [comment]
I tried the command what you shared. still getting this below error. Can you please help


info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 995 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :unityLibrary:BuildIl2CppTask FAILED
WARNING: NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [19.2.5345600] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [19.2.5345600] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
77 actionable tasks: 3 executed, 74 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/home/ramesh/Downloads/mytest/unity/builds/android/unityLibrary--compile-cpp''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/home/ramesh/Downloads/mytest/unity/builds/android/unityLibrary--compile-cpp''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (/home/ramesh/Downloads/mytest/node_modules/execa/index.js:174:9)
    at /home/ramesh/Downloads/mytest/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/home/ramesh/Downloads/mytest/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/ramesh/Downloads/mytest/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.

sdk.dir = /home/ramesh/Android/Sdk
ndk.dir=/home/ramesh/Android/Sdk/ndk/19.2.5345600

**Comment by ahalyatriton** [comment]
I tried the command what you shared for Linux. still getting this below error. Can you please help

And my sdk path
sdk.dir = /home/ramesh/Android/Sdk
ndk.dir=/home/ramesh/Android/Sdk/ndk/19.2.5345600

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 995 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :unityLibrary:BuildIl2CppTask FAILED
WARNING: NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [19.2.5345600] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [19.2.5345600] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
77 actionable tasks: 3 executed, 74 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/home/ramesh/Downloads/mytest/unity/builds/android/unityLibrary--compile-cpp''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/home/ramesh/Downloads/mytest/unity/builds/android/unityLibrary--compile-cpp''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 11s

    at makeError (/home/ramesh/Downloads/mytest/node_modules/execa/index.js:174:9)
    at /home/ramesh/Downloads/mytest/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/home/ramesh/Downloads/mytest/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/ramesh/Downloads/mytest/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by HermanLederer** [comment]
Your project is using a deprecated configuration property. Remove the `ndk.dir` line from `android/local.properties`  if one is present,  and remove it from `YOUR_UNITY_EXPORT/local.properties`. That will configure the android build to use NDK from your project modules, which is the modern way to configure it.

In case you get NDK version errors after that: you can change the NDK version in Android Studio under `File -> Project Structure -> Modules` **not under SDK location!**. Depending on your project you might need to configure it only for the unityLibrary module or the entire app. In case of React Native NDK is configured with an environment variable for the entire app and I would not recommend changing it. Usually you can change the NDK version unityLibrary requires to build in `YOUR_UNITY_EXPORT/unityLibrary/build.gradle` in

```gradle

// ...

android {
    // ...

    defaultConfig {
        minSdkVersion 21
        // ...
    }
}
```

Unity will overwrite this file every time you export unless you remove the comment on line 1 of that file.

**Comment by azesmway** [comment]
> Example won't work on windows unless change unity project/built settings/player settings/Other settings /Configuration/IL2CPP to Mono

this plugin is no longer supported
use this - https://github.com/azesmway/react-native-unity
