### ISSUE TITLE
build failed pls help

### ISSUE THREAD

**Issue by w678** [azesmway/react-native-unity-play#7]
at makeError (C:\Users\xylss\Downloads\Compressed\unityAndRN-master\unityAndRN-master\node_modules\execa\index.js:174:9)
    at C:\Users\xylss\Downloads\Compressed\unityAndRN-master\unityAndRN-master\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\xylss\Downloads\Compressed\unityAndRN-master\unityAndRN-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAn
droid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\xylss\Downloads\Compressed\unityAndRN-master\unityAndRN-master\node_modules\react-native\node_modules\@react-native-community\cli\build\
index.js:186:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unityAndRN@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unityAndRN@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xylss\AppData\Roaming\npm-cache\_logs\2021-10-11T15_35_18_293Z-debug.log

**Comment by azesmway** [comment]
> What do you meant by move your Unity project to unity folder at project root?

it was so comfortable for me. you can put where you like

**Comment by azesmway** [comment]
> [https://drive.google.com/file/d/1dU8IYr6VbUgxKaVcbu1KOYMWTL56bVAK/view?usp=sharing](url)
> 
> thanks

ok

**Comment by azesmway** [comment]
> yeah finally able to build and run but got another issue, once i run the unity game
> 
> your hardware does not support this application failed to load libmain.so


<img width="791" alt="Screenshot at Oct 12 13-31-18" src="https://user-images.githubusercontent.com/15251391/136939914-fd6eb4c4-a4c3-4d12-9d3b-4dfb8d430f84.png">

**Comment by w678** [comment]
finally able to run it, thanks a lot, but looks that it is not able to run in emulator? still got this error,

your hardware does not support this application failed to load libmain.so

**Comment by azesmway** [comment]
> hi do you know how to make the unity game in landscape mode?

I think that you can try to export in this mode and see how it will work

**Comment by azesmway** [comment]
I think yes, you need to read the documentation on how to completely unload a unity on closing
